config/routes.rb
Snootysubmit::Application.routes.draw do

  # Session Routes
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users, :except => [:index,:new,:show,:destroy,:edit] do
    collection do
      get :edit
      get :agreement
    end
  end

  match 'agreement' => 'users#agreement', :as => :agreement
  match 'signup' => 'cocktails#new', :as => :signup

  # Cocktail Resources
  resources :cocktails

  # Admin Routes
  match 'admin' => 'admin#index', :as => :admin

  # Root
  root :to => "front#index"

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  attr_accessible :name, :recipe, :user, :image
  belongs_to :user
  mount_uploader :image, ImageUploader
  
  validates :name, :presence => true
  validates :recipe, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cocktails
  
  acts_as_authentic do |c|
    # authlogic config options go here
    c.login_field = 'email'
  end
  
  attr_accessible :email, :name, :employer, :initials, :signed_date, :password, :password_confirmation
  
  validates :email, :presence => true
  validates :name, :presence => true
  validates :initials, :presence => true
  
  def admin?
    self.admin
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :require_admin
  
  def index
    @cocktails = Cocktail.find(:all,:order => "created_at")
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user_session, :current_user

  ###################################################################
  private
  
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    logger.debug "ApplicationController::require_user"
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to root_url
      return false
    end
  end

  def require_no_user
    logger.debug "ApplicationController::require_no_user"
    if current_user
      store_location
      flash[:notice] = "You must be logged out to access this page"
      return false
    end
  end

  def require_admin
    logger.debug "ApplicationController::require_admin"
    unless current_user and current_user.admin?
      redirect_to root_url
      return false
    end
  end

  def store_location
    session[:return_to] = request.url
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
  
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_filter :require_user, :except => [:new]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = current_user.cocktails.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cocktails }
    end
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @cocktail = Cocktail.find(params[:id])
    
    unless @cocktail.user.id != current_user.id and !current_user.admin?
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cocktail }
      end
    else
      flash[:notice] = "You are not allowed to view that cocktail"
      redirect_to root_url
    end
  end

  # GET /cocktails/new
  # GET /cocktails/new.json
  def new
    @cocktail = Cocktail.new    
    @user = current_user ? current_user : User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cocktail }
    end
  end

  # GET /cocktails/1/edit
  def edit
    @cocktail = Cocktail.find(params[:id])
    
    if @cocktail.user != current_user and !current_user.admin?
      flash[:notice] = "You are not allowed to edit this cocktail"
      redirect_to root_url
    end
    
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(params[:cocktail])
    @cocktail.user = current_user

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to cocktails_path, notice: 'Cocktail was successfully created.' }
        format.json { render json: @cocktail, status: :created, location: @cocktail }
      else
        format.html { render action: "new" }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cocktails/1
  # PUT /cocktails/1.json
  def update
    @cocktail = Cocktail.find(params[:id])

    unless @cocktail.user != current_user and !current_user.admin?
      respond_to do |format|
        if @cocktail.update_attributes(params[:cocktail])
          format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @cocktail.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:notice] = "You are not allowed to update this cocktail"
      redirect_to root_url
    end      
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail = Cocktail.find(params[:id])

    unless @cocktail.user != current_user and !current_user.admin?
      @cocktail.destroy

      respond_to do |format|
        format.html { redirect_to cocktails_url }
        format.json { head :no_content }
      end
    else
      flash[:notice] = "You are not allowed to edit this cocktail"
      redirect_to root_url
    end
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  layout false
  
  def index
    # this is the front page
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default root_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def agreement
    @user = current_user
  end

  def create
    @user = User.new(params[:user])
    @user.signed_date = Time.now

    if @user.save
      flash[:notice] = "Your account has been created."
      redirect_to signup_url
    else
      flash[:notice] = "There was a problem creating you."
      render :template => 'cocktails/new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to cocktails_url
    else
      render :action => :edit
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def asset_url asset
    "#{request.protocol}#{request.host_with_port}#{asset_path(asset)}"
  end
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="page-header">
  <h1>Admin</h1>
</div>

<div class="col-md-9">
	<h4>Cocktails</h4>
<table class="table table-striped">
  <thead>
    <tr>
	  <th></th>
      <th>Name</th>
	  <th>Author</th>
	  <th>Workplace</th>
	  <th>Created On</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
		<td style="vertical-align: middle;"><% if cocktail.image_url(:small).to_s != "" %><%= image_tag cocktail.image_url(:small).to_s %><% end -%></td>
        <td style="vertical-align: middle;"><%= link_to cocktail.name, cocktail_path(cocktail) %></td>
		<td style="vertical-align: middle;"><%= cocktail.user != nil ? cocktail.user.name : "Unknown" %></td>
		<td style="vertical-align: middle;"><%= cocktail.user != nil ? cocktail.user.employer : "Unknown" %></td>
		<td style="vertical-align: middle;"><%= cocktail.created_at.strftime("%B %d, %Y") %></td>
        <td class="text-right">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cocktail_path(cocktail), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cocktail_path(cocktail),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="col-md-3">
	<h4>Users</h4>
	
	<p>
	<% @users.each do |user| %>
		<%= mail_to user.email, user.name %><br/>
	<% end %>
	</p>
</div>

app/views/cocktails/edit.html.erb
<%- model_class = Cocktail -%>

<div class="page-header">
  <h3>Edit &#8220;<%= @cocktail.name %>&#8221;</h3>
</div>

<%= render :partial => 'form' %>

app/views/cocktails/index.html.erb
<%- model_class = Cocktail -%>
<div class="page-header">
  <h1>Your Cocktails</h1>
</div>

<% if @cocktails.length > 0 -%>
<p class="spaced">
	<strong>Thanks for submitting <% if @cocktails.length > 1 -%>cocktail recipes<% else -%>a cocktail recipe<% end -%>
	to the San Diego Cocktail Book Project!</strong>  We will be in contact soon via the e-mail address that you provided.  
	If you need to reach out to us, please <a href="mailto:jeff@jeffreynichols.com">send an e-mail to Jeff</a>.
</p>
<% end -%>

<p class="smallspaced">
	If you need to edit your contact information, <%= link_to "click here", edit_users_path %>.
</p>

<p class="smallspaced">
	You agreed to the intellectual property agreement on <%= current_user.signed_date %> with the initials <%= current_user.initials %>.
	To view the agreement again, <%= link_to "click here", agreement_path %>.
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td style="vertical-align: middle;"><%= link_to cocktail.name, cocktail_path(cocktail) %></td>
        <td class="text-right">
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cocktail_path(cocktail), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cocktail_path(cocktail),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cocktail_path,
            :class => 'btn btn-primary' %>

app/views/cocktails/new.html.erb
<% if current_user == nil -%>

	<%- model_class = User -%>
	<div class="page-header">
	  <h1>Welcome!</h1>
	</div>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<% if @user.errors.any? -%>
				<%= render "shared/error_messages", :target => @user %>
			<% else -%>
				<p class="lead">
					Thanks for considering submitting cocktail recipes to the San Diego Cocktail Book project!
				</p>
				
				<p class="spaced">
					If you submitted a cocktail previously, please <%= link_to "login first!", login_path %>
				</p>
	
				<p class="spaced">
					Before you enter your recipes, we need to collect some contact information and take care of 
					some legal matters.  The contact information will be used only to communicate with you about
					the book.  The legal agreement allows us to publish your recipes and any other content you 
					submit to us, however you retain full ownership and rights to anything you submit.  It
					also protects us in the event that you submit information to which you do not own the rights.
				</p>
			<% end -%>
		</div>
	</div>
	  
	<%= form_for @user do |f| %>

	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h3 class="text-center">contact information</h3>
		
			  <div class="form-group spaced">
			    <%= f.label "Your full name:" %>
			    <%= f.text_field :name, :class => 'form-control' %>
			  </div>

			  <div class="form-group spaced">
			    <%= f.label "Your e-mail address:" %>
			    <%= f.text_field :email, :class => 'form-control', :type => :email %>
				<span class="help-block"><small>We'll only use this to contact you about the book.</small></span>
			  </div>

			  <div class="form-group spaced">
			    <%= f.label "Your current employer:" %>
			    <%= f.text_field :employer, :class => 'form-control' %>
				<span class="help-block"><small>OPTIONAL. This will help us plan photography sessions, etc.</small></span>
			  </div>

			  <div class="form-group spaced">
			    <%= f.label "Password:", :class => 'control-label' %>
			    <%= f.password_field :password, :class => 'form-control' %>
				<span class="help-block"><small>Providing a password allows you to edit your submissions later.</small></span>
			  </div>

			  <div class="form-group">
			    <%= f.label "Password Confirmation:", :class => 'control-label' %>
			    <%= f.password_field :password_confirmation, :class => 'form-control' %>
			  </div>
		</div>
	</div>

	<div class="row rowspacer50">
		<div class="col-md-6 col-md-offset-3">
			<h3 class="text-center">legal stuff</h3>
			
			<p class="spaced">
				Please read this fully!
			</p>
		</div>
	</div>
	
	<div class="row rowspacer25" style="margin-top: 25px;">
		<div class="col-md-10 col-md-offset-1">
			<div class="well">
				<%= render :partial => 'shared/agreement' %>
			</div>
		</div>
	</div>
	
	<div class="row rowspacer25" style="margin-top: 25px;">
		<div class="col-md-6 col-md-offset-3">
			<div class="form-group">
	    		<%= f.label "Please initial here to confirm you agree to the above terms:", :class => 'control-label' %>
				<%= f.text_field :initials, :class => 'form-control' %>
			</div>
	    </div>
	</div>

	<div class="row rowspacer25" style="margin-top: 25px;">
		<div class="col-md-6 col-md-offset-3">
			<div class="form-actions text-center">
				<%= f.submit "Agree and Continue", :class => 'btn btn-primary' %>
				<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	                root_url, :class => 'btn' %>
	  		</div>
		</div>
	</div>
	
	<% end  # form end -%>
<% else -%>
	<%- model_class = Cocktail -%>
	<div class="page-header">
	  <h1>Submit new cocktail</h1>
	</div>
	
	<%= render "shared/error_messages", :target => @cocktail %>
	
	<%= render :partial => 'form' %>
<% end -%>

app/views/front/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>San Diego Cocktail Book Project</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:url" content="http://sdcocktailbook.com/"/>
  <meta property="og:title" content="San Diego Cocktail Book Project"/>
  <meta property="og:description" content="Celebrating the wealth and breadth of San Diego cocktail culture with contributions from area bartenders."/>
  <meta property="og:image" content="<%= asset_url('facebook-link-image.png') %>"/>
</head>
<body class="title-body">

	<div class="jumbotron drink-title">

		<div class="navbar navbar-default navbar-transparent" role="navigation">
			<div class="container">
				<div class="navbar-header">
		      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
		        		<span class="icon-bar"></span>
		        		<span class="icon-bar"></span>
		        		<span class="icon-bar"></span>
					</button>
		      	</div>
		      	<div class="collapse navbar-collapse" id="navbar-collapse">
			        <ul class="nav navbar-nav pull-right">
					  <% if current_user != nil -%>
			          	<li><%= link_to "My Cocktails", cocktails_path %></li>
						<% if current_user.admin? -%>
							<li><%= link_to "Admin", admin_path %></li>
						<% end -%>
					  <% end -%>
						<li><a href="http://blog.whatdididrink.com/">Blog</a></li>
					  <% if current_user == nil -%>
						<li><%= link_to "Login", login_path %></li>
					  <% else -%>
						<li><%= link_to "Logout", logout_path %></li>
					  <% end -%>
					</ul>
				</div>
		    </div>
		</div>

		<div class="container">
			<div class="col-xs-6 title-column">
				<h1 class="h1-title title-color">
					San Diego<br/>
					Cocktail Book<br/> 
					Project
				</h1>
				<p class="subtitle">
					Celebrating the wealth and breadth of San Diego cocktail culture with contributions from area bartenders.
				</p>
				<p><%= link_to "Submit your cocktails!", new_cocktail_path, :class => "btn btn-primary btn-lg", :role => "button" %></p>
			</div>
		</div>
	</div>
	
	<div class="container">
		<div class="row rowspace50">
			<div class="col-md-6 col-md-offset-3">
				<h2 class="text-center">our vision</h2>
		
				<p class="spaced">
					We think San Diego is a great cocktail town with a huge breadth of interesting
					people creating and serving up quality drinks.  Unfortunately, except for a couple
					of the best known spots, we don't think the cocktail culture in this city gets
					enough of the publicity and acclaim outside of the city as it should.  When 
					people think of west coast cocktail cities, they think of Portland, San Francisco,
					Los Angeles and Seattle, and we think it's a shame that San Diego is often missing.
				</p>
				
				<p class="spaced lead">
					To help address this, we are putting together a high quality cocktail book that
					features the drinks and people of our city.  
				</p>
				
				<p class="spaced">
					The book will be professionally done and sold on Amazon and hopefully other retailers.
					We will balance accessibility between a mainstream audience and the bartending crowd, 
					featuring lots of high quality drink photography, some basic cocktail making instruction, 
					and some recipes that are surprising and appeal to an experienced palette.
				</p>
				
				<p class="spaced">
					We are still working out the overall design, but we expect to borrow concepts from 
					previous cocktail books, such as <a href="http://www.amazon.com/gp/product/0982631502/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0982631502&linkCode=as2&tag=why07b-20&linkId=SQXP7SIQU662QH2P">Left Coast Libations</a> and 
					<a href="http://www.amazon.com/gp/product/158008253X/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=158008253X&linkCode=as2&tag=why07b-20&linkId=C5JTYX3FB5FZYDRO">Speakeasy</a>.
				</p>
				
				<p class="spaced">
					This is not our first cocktail book, though it is a bigger undertaking than what we've
					done before.  Our first book, which you can see below, was designed to be more of a 
					coffee table book, yet include enough instruction to get newbies off the ground.
				</p>
				
				<div style='width: 100%; margin-top: 30px;'>
				  <object class='myWidget' data='http://www.blurb.com/assets/embed.swf' height='200' type='application/x-shockwave-flash' width='350'>
				    <param name='allowFullScreen' value='true' />
				    <param name='wmode' value='transparent' />
				    <param name='allowScriptAccess' value='always' />
				    <param name='movie' value='http://www.blurb.com/assets/embed.swf' />
				    <param name='FlashVars' value='book_id=4908138&amp;locale=en_US' />
				    <a href='http://www.blurb.com/books/4908138' target='_new'>
				      	<img src='http://assets3.blurb.com/images/uploads2/catalog/002/721/821/5290274-3321526b4aea6d4b45327e420147b089.jpg' id="backup-book-image"/>
				    </a>
				  </object>
				</div>
			</div>
		</div>
		
		<div class="row rowspace50">
			<div class="col-md-6 col-md-offset-3">
				<h2 class="text-center">to participate...</h2>
		
				<p class="spaced lead">
					For the book to be a success, we need your contributions!
				</p>
				
				<p class="spaced">
					We will evaluate all submitted recipes and make rolling decisions as
					to which will be included in the book, though we expect that most submitted
					recipes will be included.  If we decide to include your recipe(s), we will
					reach out to you by e-mail to schedule a photo session and interview.  You
					will also get to see proofs of any pages including your content, as well as 
					a final proof when the book is complete before it goes to print.  We hope to 
					give a complimentary copy of the book to each contributor once it is published,
					though this will depend on the cost of printing and the book's success.
				</p>

				<p class="spaced">
					Click the button below to get started.  We would like to have most 
					recipes submitted by <strong>June 30, 2014</strong>, but we will
					consider submissions through the end of the summer.
				</p>
				
				<p class="spaced text-center">
					<%= link_to "Submit your cocktails!", new_cocktail_path, :class => "btn btn-primary btn-lg", :role => "button" %>
				</p>
				
				<p class="spaced">
					If you have any questions, feel free to contact us via 
					<a href="http://facebook.com/sdcocktailbook">the Facebook page</a> or by 
					<a href="mailto:jeff@jeffreynichols.com">e-mail</a>.
				</p>
			</div>
		</div>
		
		<div class="row rowspace50">
			<div class="col-md-6 col-md-offset-3 testborder">
				<h2 class="text-center">the organizers</h2>
				
				<p class="text-left spaced">
					We're cocktail enthusiasts, not bartenders, but you
					probably wouldn't know it from the amount of time
					we spend in bars. If you work at a bar, there's a good 
					chance that we've sat in front of you at least once before.
				</p>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-3 col-md-offset-2 testborder rowspace50">
				<%= image_tag "jeff_reasonably_small.jpg", :class => 'bio-image' %>
				
				<h5 class="text-center">Jeffrey Nichols</h5>
				
				<p>
					Jeff is research scientist at Google and
					resident of downtown San Diego.  He will drink
					anything boozy and bitter, but also enjoys a 
					well made tiki cocktail.
				</p>
			</div>
			
			<div class="col-md-3 col-md-offset-2 testborder rowspace50">
				<%= image_tag "jordan_small.jpg", :class => 'bio-image' %>
				
				<h5 class="text-center">Clayton Jordan III</h5>
				
				<p>
					Jordan is a supply chain management expert who
					works in north county.  He prefers rye whiskey
					and likes lavender bitter cocktails when he can
					find them.
				</p>
			</div>
		</div>
	</div>
	
	<div class="footer" id="footer">
		<div class="footer-content container">
			<div class="col-md-6">
				<p><small>Copyright &copy; 2014, Snooty Bird, LLC</small></p>
			</div>
			<div class="col-md-6 text-right">
				<p><small>For questions and information, please contact <a href="mailto:jeff@jeffreynichols.com">Jeff</a>.</small></p>
			</div>
		</div>
	</div>
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-51633029-1', 'sdcocktailbook.com');
	  ga('send', 'pageview');

	</script>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>San Diego Cocktail Book Project</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:url" content="http://sdcocktailbook.com/"/>
  <meta property="og:title" content="San Diego Cocktail Book Project"/>
  <meta property="og:description" content="Celebrating the wealth and breadth of San Diego cocktail culture with contributions from area bartenders."/>
  <meta property="og:image" content="<%= asset_url('facebook-link-image.png') %>"/>
</head>
<body>

	<div class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
	      		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
	        		<span class="icon-bar"></span>
				</button>
	      	</div>
	      	<div class="collapse navbar-collapse" id="navbar-collapse">
				<ul class="nav navbar-nav">
					<li><%= link_to "Home", root_url %></li>
				</ul>
		        <ul class="nav navbar-nav pull-right">
					<% if current_user != nil -%>
			          	<li><%= link_to "My Cocktails", cocktails_path %></li>
						<% if current_user.admin? -%>
							<li><%= link_to "Admin", admin_path %></li>
						<% end -%>
					<% end -%>
					<li><a href="http://blog.whatdididrink.com/">Blog</a></li>
				    <% if current_user == nil -%>
					  <li><%= link_to "Login", login_path %></li>
				    <% else -%>
					  <li><%= link_to "Logout", logout_path %></li>
				    <% end -%>
				</ul>
	      	</div>
	    </div>
	</div>    

	<div class="container">
		<%= yield %>
	</div>

	<div class="footer" id="footer">
		<div class="footer-content container">
			<div class="col-md-6">
				<p><small>Copyright &copy; 2014, Snooty Bird, LLC</small></p>
			</div>
			<div class="col-md-6 text-right">
				<p><small>For questions and information, please contact <a href="mailto:jeff@jeffreynichols.com">Jeff</a>.</small></p>
			</div>
		</div>
	</div>
	
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-51633029-1', 'sdcocktailbook.com');
	  ga('send', 'pageview');

	</script>
	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
</body>
</html>

app/views/user_sessions/new.html.erb
<%- model_class = UserSession -%>
<div class="page-header">
  <h1>Welcome back!</h1>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<p>
			If you don't have an account yet, <%= link_to "register for one here.", new_cocktail_path %>
		</p>
		
		<%= form_for @user_session, :as => :user_session, :url => { :action => "create" } do |f| %>
			<%= render "shared/error_messages", :target => @user_session %>

			<div class="form-group spaced">
				<%= f.label :email %>
				<%= f.text_field :email, :class => 'form-control', :type => :email %>
			</div>

			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, :class => 'form-control' %>
			</div>

			<div class="checkbox">
				<%= f.label :remember_me do %>
					<%= f.check_box :remember_me %> 
					Remember Me
				<% end -%>
			</div>

			<div class="form-actions">
				<%= f.submit "Login", :class => 'btn btn-primary' %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>Edit <%= @user.name %></h1>
</div>

<%= render :partial => 'form' %>